name: Deployment pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:

  simple_deployment_pipeline:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: github context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: commits
        env:
          COMMITS: ${{ toJson(github.event.commits) }}
        run: echo "$COMMITS"
        
      - name: commit messages
        run: |
          echo "COMMIT_MESSAGES=$(echo "${{ toJson(github.event.commits.*.message) }}" | jq -r '.[]' | tr '\n' ',')" >> $GITHUB_ENV
      
      - name: echo commit messages
        run: echo "${{ env.COMMIT_MESSAGES }}"
        
      - name: join commit messages
        run: echo "JOINT_COMMIT_MESSAGES=$(echo '${{ env.COMMIT_MESSAGES }}' | tr -d '[]\" ')" >> $GITHUB_ENV

      - name: echo joined commit messages
        run: echo "${{ env.JOINT_COMMIT_MESSAGES }}"

      - name: Install dependencies
        run: npm install

      - name: Check style
        run: npm run eslint

      - name: Build
        run: npm run build

      - name: Test
        run: npm test

      - name: Trigger deployment
        run: curl https://api.render.com/deploy/srv-${{ secrets.RENDER_SERVICE_ID }}?key=${{ secrets.RENDER_API_KEY }}
        if: ${{ github.event_name == 'push' && !contains(env.JOINT_COMMIT_MESSAGES, '#skip') }}

  tag_release:
    needs: [simple_deployment_pipeline]
    runs-on: ubuntu-20.04
    steps: 
      - uses: actions/checkout@v4
      - name: Bump version and push tag
        if: ${{ github.event_name == 'push' && !contains(env.JOINT_COMMIT_MESSAGES, '#skip') }}
        uses: anothrNick/github-tag-action@1.70.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}